env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 140
    lines: 45

  padding:
    x: 1
    y: 1

  decorations: none

  # Window title
  title: a

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    family: SauceCodePro Nerd Font
    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    family: SauceCodePro Nerd Font

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    family: SauceCodePro Nerd Font

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    family: SauceCodePro Nerd Font
    # The `style` can be specified to pick a specific face.
    style: Bold Italic
  # Point size, this is what is known as the font size
  size: 16.0
  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 1

  # Thin stroke font rendering (macOS only)
  use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# Colors (Blood Moon)
colors:
  # Default colors
  primary:
    background: '#10100E'
    foreground: '#C6C6C4'

  # Normal colors
  normal:
    black:   '#10100E'
    red:     '#C40233'
    green:   '#009F6B'
    yellow:  '#FFD700'
    blue:    '#0087BD'
    magenta: '#9A4EAE'
    cyan:    '#20B2AA'
    white:   '#C6C6C4'

  # Bright colors
  bright:
    black:   '#696969'
    red:     '#FF2400'
    green:   '#03C03C'
    yellow:  '#FFD700'
    blue:    '#007FFF'
    magenta: '#FF1493'
    cyan:    '#00CCCC'
    white:   '#FFFAFA'

# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 1.0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Allow terminal applications to change Alacritty's window title.
dynamic_title: false

cursor:
  style: Block

# Live config reload (changes require restart)
live_config_reload: true

shell:
  program: /bin/bash
  args:
    - -l
    - -c
    - "tmux attach || tmux new -s main"

alt_send_esc: true
# Use xxd -psd to get chars code, need this because alt_send_esc doesn't seem to be doing anything...
# xdd -psd will return a string like 1b620a, Split this up to 1b, 62, and 0a, the 0a is the return character. So skip it.
key_bindings:
    #Get alt/option + b to jump back a character
  - { key: B, mods: Alt, chars: "\x1b\x62"}
    #Get alt/option + f to jump back a character
  - { key: F, mods: Alt, chars: "\x1b\x66"}
    #Create a new tmux pane
  - { key: T, mods: Command, chars: "\x01\x63"}
    #Kill a new tmux pane
  - { key: W, mods: Command, chars: "\x01\x78"}
    #Emulate iterm Command + Shift + D to split horizontal in tmux
  - { key: D, mods: Command|Shift, chars: "\x01\x2d"}
    #Emulate iterm Command + D vertical split in tmux
  - { key: D, mods: Command, chars: "\x01\x7c"}
    #Jump to window 1 with cmd + 1
  - { key: Key1, mods: Command, chars: "\x01\x31" }
    #Jump to window 2 with cmd + 2
  - { key: Key2, mods: Command, chars: "\x01\x32" }
    #Jump to window 3 with cmd + 3
  - { key: Key3, mods: Command, chars: "\x01\x33" }
    #Jump to window 4 with cmd + 4
  - { key: Key4, mods: Command, chars: "\x01\x34" }
    #Jump to window 5 with cmd + 5
  - { key: Key5, mods: Command, chars: "\x01\x35" }
    #Jump to window 6 with cmd + 6
  - { key: Key6, mods: Command, chars: "\x01\x36" }
    #Jump to window 7 with cmd + 7
  - { key: Key7, mods: Command, chars: "\x01\x37" }
    #Go fullscreen! It's level 9000!
  - { key: Return, mods: Command, action: ToggleFullScreen }
    #Go to prev tmux pane
  - { key: LBracket, mods: Command, chars: "\x01\x70" }
    #Go to next tmux pane
  - { key: RBracket, mods: Command, chars: "\x01\x6e" }
