style:
  tag:
    color: cyan # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 1 # column width relative to the terminal window
    min_width: 15 # minimum column width as number of characters
  snippet:
    color: dark_green
  comment:
    color: white
    width_percentage: 30
    min_width: 30

finder:
  command: fzf # equivalent to the --finder option

cheats:
   paths: 
     - ~/.dotfiles/.navi/cheats
     - ~/.navi_cheats

# search:
  # tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: bash # shell used for shell out. possible values: bash, zsh, dash, ...
